<?php
echo "<pre>";
echo(
    base64_decode(
    "IERXRFcgICAgICBEVyAgICAgICAgICBEVzxicj4gRFcgIERXICAgIERXICAgICAgICAgIERXPGJyPiBEVyAgICBEVyAgRFcgICAgRFcgICAgRFc8YnI+IERXICAgIERXICBEVyAgRFdEV0RXICBEVzxicj4gRFcgIERXICAgIERXRFcgICAgICBEV0RXPGJyPiBEV0RXICAgICAgRFcgICAgICAgICAgRFc8YnI+CQ===="
    )
);
echo "</pre>";
?>